use derive_empty_traits::EmptyTraits;
use resolver_api::Resolve;
use serde::{Deserialize, Serialize};
use typeshare::typeshare;

use crate::entities::{
  I64, server::_PartialServerConfig,
  server_onboarding_key::ServerOnboardingKey,
};

use super::KomodoWriteRequest;

//

/// **Admin only.** Create a Server onboarding key.
/// Response: [CreateServerOnboardingKeyResponse].
///
/// Note. The 'periphery_public_key' on default Server config will
/// be overridden with the actual public key once its generated by Periphery
/// as part of the onboarding flow.
#[typeshare]
#[derive(
  Serialize, Deserialize, Debug, Clone, Resolve, EmptyTraits,
)]
#[empty_traits(KomodoWriteRequest)]
#[response(CreateServerOnboardingKeyResponse)]
#[error(serror::Error)]
pub struct CreateServerOnboardingKey {
  /// The name for the creation key
  pub name: String,
  /// A unix timestamp in millseconds specifying api key expire time.
  /// Default is 0, which means no expiry.
  #[serde(default)]
  pub expires: I64,
  /// Optionally specify an existing private key, otherwise
  /// generate fresh key.
  pub private_key: Option<String>,
  /// Default tags to apply to Servers created using this key.
  #[serde(default)]
  pub default_tags: Vec<String>,
  /// Default config to apply to Servers created using this key
  #[serde(default)]
  pub default_config: _PartialServerConfig,
}

/// The response for [CreateServerOnboardingKey]
#[typeshare]
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct CreateServerOnboardingKeyResponse {
  /// pkcs8 encoded private key
  pub private_key: String,
  /// The created ServerOnboardingKey
  pub created: ServerOnboardingKey,
}

//

/// **Admin only.** Delete a creation key.
/// Response: The deleted [ServerOnboardingKey].
#[typeshare]
#[derive(
  Serialize, Deserialize, Debug, Clone, Resolve, EmptyTraits,
)]
#[empty_traits(KomodoWriteRequest)]
#[response(DeleteServerOnboardingKeyResponse)]
#[error(serror::Error)]
pub struct DeleteServerOnboardingKey {
  pub public_key: String,
}

#[typeshare]
pub type DeleteServerOnboardingKeyResponse = ServerOnboardingKey;
